font_family      JetBrains Mono Nerd Font
font_size        12.0
background       #000000
background_opacity 0.85
foreground       #FFFFFF
selection_background #FFFFFF
selection_foreground #000000
cursor           #FFFFFF
color0  #000000
color1  #FFFFFF
color2  #E6EAF2
color4  #FFFFFF
color5  #E6EAF2
