foreground            #e0e2e8
background            #101418
cursor                #9acbfa
selection_foreground  #101418
selection_background  #9acbfa
color1  #ffb4ab
color2  #d3bfe6
color4  #9acbfa
color5  #b9c8da
